// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef _TFT_28_UI_H
#define _TFT_28_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Welcome.h"
#include "ui_WiFiSetting.h"
#include "ui_Time.h"
#include "ui_Keqing.h"
#include "ui_Move.h"
#include "ui_CalendarDecor.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_388382192);    // assets/left-arrow.png
LV_IMG_DECLARE(ui_img_385938922);    // assets/refresh-arrow.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/thermometer.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_84851999);    // assets/day-mode.png
LV_IMG_DECLARE(ui_img_night_png);    // assets/night.png
LV_IMG_DECLARE(ui_img_e64e7b6136a1e0cb7f04b9ab829ff3ff_png);    // assets/e64e7b6136a1e0cb7f04b9ab829ff3ff.png
LV_IMG_DECLARE(ui_img_bc5a74564f30248025888e7f7f8e175b_png);    // assets/bc5a74564f30248025888e7f7f8e175b.png
LV_IMG_DECLARE(ui_img_537571085);    // assets/HPBD (Custom).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
