// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_Calendar = NULL;
lv_obj_t * ui_CalendarSetting = NULL;
// event funtions
void ui_event_CalendarSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_screen_change(&ui_SettingTimeManually, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingTimeManually_screen_init);
        SetDayManually(e);
    }
}

// build funtions

void ui_Calendar_screen_init(void)
{
    ui_Calendar = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Calendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalendarSetting = lv_calendar_create(ui_Calendar);
    lv_calendar_set_today_date(ui_CalendarSetting, 2026, 8, 2);
    lv_calendar_set_showed_date(ui_CalendarSetting, 2026, 8);
    lv_obj_t * ui_CalendarSetting_header = lv_calendar_header_arrow_create(ui_CalendarSetting);
    lv_obj_set_width(ui_CalendarSetting, 320);
    lv_obj_set_height(ui_CalendarSetting, 240);
    lv_obj_set_align(ui_CalendarSetting, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_CalendarSetting, ui_event_CalendarSetting, LV_EVENT_ALL, NULL);

}

void ui_Calendar_screen_destroy(void)
{
    if(ui_Calendar) lv_obj_del(ui_Calendar);

    // NULL screen variables
    ui_Calendar = NULL;
    ui_CalendarSetting = NULL;

}
