// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_CALENDAR1_H
#define UI_CALENDAR1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calendar1
extern void ui_Calendar1_screen_init(void);
extern void ui_Calendar1_screen_destroy(void);
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_CalendarSetting1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

