// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_CALENDARDECOR_H
#define UI_CALENDARDECOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalendarDecor
extern void ui_CalendarDecor_screen_init(void);
extern void ui_CalendarDecor_screen_destroy(void);
extern lv_obj_t * ui_CalendarDecor;
extern lv_obj_t * ui_CalendarD;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

