// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_Calendar1 = NULL;
lv_obj_t * ui_CalendarSetting1 = NULL;
// event funtions

// build funtions

void ui_Calendar1_screen_init(void)
{
    ui_Calendar1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Calendar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalendarSetting1 = lv_calendar_create(ui_Calendar1);
    lv_calendar_set_today_date(ui_CalendarSetting1, 2026, 8, 2);
    lv_calendar_set_showed_date(ui_CalendarSetting1, 2026, 8);
    lv_obj_t * ui_CalendarSetting1_header = lv_calendar_header_arrow_create(ui_CalendarSetting1);
    lv_obj_set_width(ui_CalendarSetting1, 320);
    lv_obj_set_height(ui_CalendarSetting1, 240);
    lv_obj_set_align(ui_CalendarSetting1, LV_ALIGN_CENTER);

}

void ui_Calendar1_screen_destroy(void)
{
    if(ui_Calendar1) lv_obj_del(ui_Calendar1);

    // NULL screen variables
    ui_Calendar1 = NULL;
    ui_CalendarSetting1 = NULL;

}
