// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_CalendarDecor = NULL;
lv_obj_t * ui_CalendarD = NULL;
// event funtions

// build funtions

void ui_CalendarDecor_screen_init(void)
{
    ui_CalendarDecor = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalendarDecor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalendarD = lv_calendar_create(ui_CalendarDecor);
    lv_calendar_set_today_date(ui_CalendarD, 2026, 8, 2);
    lv_calendar_set_showed_date(ui_CalendarD, 2026, 8);
    lv_obj_t * ui_CalendarD_header = lv_calendar_header_arrow_create(ui_CalendarD);
    lv_obj_set_width(ui_CalendarD, 320);
    lv_obj_set_height(ui_CalendarD, 240);
    lv_obj_set_align(ui_CalendarD, LV_ALIGN_CENTER);

}

void ui_CalendarDecor_screen_destroy(void)
{
    if(ui_CalendarDecor) lv_obj_del(ui_CalendarDecor);

    // NULL screen variables
    ui_CalendarDecor = NULL;
    ui_CalendarD = NULL;

}
