// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_CALENDAR_H
#define UI_CALENDAR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calendar
extern void ui_Calendar_screen_init(void);
extern void ui_Calendar_screen_destroy(void);
extern lv_obj_t * ui_Calendar;
extern void ui_event_CalendarSetting(lv_event_t * e);
extern lv_obj_t * ui_CalendarSetting;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

