// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

void connectWifFi(lv_event_t * e)
{
	// Your code here
}

void saveTimeManually(lv_event_t * e)
{
	// Your code here
}

void SetDayManually(lv_event_t * e)
{
	// Your code here
}
