// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"
#include <global_help.h>

void connectWifFi(lv_event_t * e)
{
	WiFiData wifiData;
	lv_dropdown_get_selected_str(ui_WiFiList, wifiData.ssid, sizeof(wifiData.ssid));
	strcpy(wifiData.pass, lv_textarea_get_text(ui_WiFiPass));
	xQueueSend(WiFiInfo, &wifiData, portMAX_DELAY);
	
}

void saveTimeManually(lv_event_t * e)
{
	int hourGet = lv_spinbox_get_value(ui_Spinbox1);
	int minuteGet = lv_spinbox_get_value(ui_Spinbox2);
	int secondGet = 0;

	timeData time = {hourGet, minuteGet, secondGet};
	xQueueSend(TimeHandle, &time, portMAX_DELAY);
}

void SetDayManually(lv_event_t * e)
{
	lv_calendar_date_t date;
	lv_calendar_get_pressed_date(ui_CalendarSetting, &date);
	dayData day = {(int)date.day, (int)date.month, (int)date.year};
	lv_label_set_text_fmt(ui_DaySetting, "%02d-%02d-%04d", (int)day.day, (int)day.month, (int)day.year);
	xQueueSend(DayHandle, &day, portMAX_DELAY);
}

void scanWifiCall(lv_event_t * e)
{
	request_wifi_scan = true;
}

void groupKeyboard(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = (lv_obj_t *)lv_event_get_target(e);

    // Khi Joystick nhấn ENTER vào ô này
    if (code == LV_EVENT_CLICKED) { 
        // Hiện bàn phím và liên kết nó với ô Password
        lv_obj_remove_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN); 
        lv_keyboard_set_textarea(ui_Keyboard1, ta);

        // BẮT BUỘC: Đưa bàn phím vào Group và gán Focus cho nó
        lv_group_add_obj(joystick_group, ui_Keyboard1);
        lv_group_focus_obj(ui_Keyboard1);

		lv_group_set_editing(joystick_group, true);
        
        Serial.println("[KEYBOARD] Đã nhảy Focus vào Bàn phím ảo!");
    }
}
