// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_KEQING_H
#define UI_KEQING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Keqing
extern void ui_Keqing_screen_init(void);
extern void ui_Keqing_screen_destroy(void);
extern lv_obj_t * ui_Keqing;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

