// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_MOVE_H
#define UI_MOVE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Move
extern void ui_Move_screen_init(void);
extern void ui_Move_screen_destroy(void);
extern lv_obj_t * ui_Move;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

