// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_SETTINGTIMEMANUALLY_H
#define UI_SETTINGTIMEMANUALLY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingTimeManually
extern void ui_SettingTimeManually_screen_init(void);
extern void ui_SettingTimeManually_screen_destroy(void);
extern lv_obj_t * ui_SettingTimeManually;
extern lv_obj_t * ui_HourSetting;
extern lv_obj_t * ui_Spinbox1;
extern lv_obj_t * ui_Spinbox2;
extern lv_obj_t * ui_colon;
extern lv_obj_t * ui_HourLabel;
extern lv_obj_t * ui_MinuteLabel;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_DaySetting;
extern void ui_event_SaveTimeButton(lv_event_t * e);
extern lv_obj_t * ui_SaveTimeButton;
extern lv_obj_t * ui_SaveTime;
extern lv_obj_t * ui_Image4;
extern void ui_event_CalendarButton(lv_event_t * e);
extern lv_obj_t * ui_CalendarButton;
extern void ui_event_TimeSetting(lv_event_t * e);
extern lv_obj_t * ui_TimeSetting;
extern void ui_event_BackToWelcome2(lv_event_t * e);
extern lv_obj_t * ui_BackToWelcome2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

