// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_SettingTimeManually = NULL;
lv_obj_t * ui_HourSetting = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_Spinbox2 = NULL;
lv_obj_t * ui_colon = NULL;
lv_obj_t * ui_HourLabel = NULL;
lv_obj_t * ui_MinuteLabel = NULL;
lv_obj_t * ui_TimeSetting = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_DaySetting = NULL;
lv_obj_t * ui_CalendarButton = NULL;
lv_obj_t * ui_SaveTimeButton = NULL;
lv_obj_t * ui_SaveTime = NULL;
lv_obj_t * ui_BackToWelcome2 = NULL;
// event funtions
void ui_event_TimeSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveTimeManually(e);
    }
}

void ui_event_CalendarButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Calendar_screen_init);
    }
}

void ui_event_SaveTimeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}

void ui_event_BackToWelcome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Welcome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Welcome_screen_init);
    }
}

// build funtions

void ui_SettingTimeManually_screen_init(void)
{
    ui_SettingTimeManually = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingTimeManually, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourSetting = lv_obj_create(ui_SettingTimeManually);
    lv_obj_set_width(ui_HourSetting, 170);
    lv_obj_set_height(ui_HourSetting, 80);
    lv_obj_set_x(ui_HourSetting, 0);
    lv_obj_set_y(ui_HourSetting, -70);
    lv_obj_set_align(ui_HourSetting, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HourSetting, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_HourSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HourSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HourSetting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HourSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_HourSetting);
    lv_obj_set_width(ui_Spinbox1, 60);
    lv_obj_set_height(ui_Spinbox1, 48);
    lv_obj_set_y(ui_Spinbox1, 9);
    lv_obj_set_x(ui_Spinbox1, lv_pct(-30));
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 2, 0);
    lv_spinbox_set_range(ui_Spinbox1, 0, 23);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);
    lv_obj_set_style_bg_image_recolor(ui_Spinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Spinbox1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Spinbox2 = lv_spinbox_create(ui_HourSetting);
    lv_obj_set_width(ui_Spinbox2, 60);
    lv_obj_set_height(ui_Spinbox2, 48);
    lv_obj_set_y(ui_Spinbox2, 9);
    lv_obj_set_x(ui_Spinbox2, lv_pct(30));
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox2, 2, 0);
    lv_spinbox_set_range(ui_Spinbox2, 0, 59);
    lv_spinbox_set_cursor_pos(ui_Spinbox2, 1 - 1);
    lv_obj_set_style_text_font(ui_Spinbox2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_colon = lv_label_create(ui_HourSetting);
    lv_obj_set_width(ui_colon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_colon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_colon, 0);
    lv_obj_set_y(ui_colon, 9);
    lv_obj_set_align(ui_colon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_colon, ":");

    ui_HourLabel = lv_label_create(ui_HourSetting);
    lv_obj_set_width(ui_HourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourLabel, lv_pct(-30));
    lv_obj_set_y(ui_HourLabel, lv_pct(-50));
    lv_obj_set_align(ui_HourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourLabel, "Hour");

    ui_MinuteLabel = lv_label_create(ui_HourSetting);
    lv_obj_set_width(ui_MinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteLabel, lv_pct(30));
    lv_obj_set_y(ui_MinuteLabel, lv_pct(-50));
    lv_obj_set_align(ui_MinuteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinuteLabel, "Minute");

    ui_TimeSetting = lv_imagebutton_create(ui_SettingTimeManually);
    lv_imagebutton_set_src(ui_TimeSetting, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_check_png, NULL);
    lv_obj_set_width(ui_TimeSetting, 32);
    lv_obj_set_height(ui_TimeSetting, 32);
    lv_obj_set_x(ui_TimeSetting, 112);
    lv_obj_set_y(ui_TimeSetting, -62);
    lv_obj_set_align(ui_TimeSetting, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_TimeSetting, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_TimeSetting, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_TimeSetting, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_TimeSetting, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Panel1 = lv_obj_create(ui_SettingTimeManually);
    lv_obj_set_width(ui_Panel1, 310);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 13);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Panel1, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_DaySetting = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_DaySetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DaySetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DaySetting, -14);
    lv_obj_set_y(ui_DaySetting, 0);
    lv_obj_set_align(ui_DaySetting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DaySetting, "02-08-2026");
    lv_obj_set_style_text_font(ui_DaySetting, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalendarButton = lv_imagebutton_create(ui_SettingTimeManually);
    lv_imagebutton_set_src(ui_CalendarButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_calendar_png, NULL);
    lv_obj_set_width(ui_CalendarButton, 32);
    lv_obj_set_height(ui_CalendarButton, 32);
    lv_obj_set_x(ui_CalendarButton, 115);
    lv_obj_set_y(ui_CalendarButton, 12);
    lv_obj_set_align(ui_CalendarButton, LV_ALIGN_CENTER);
    lv_obj_set_style_outline_color(ui_CalendarButton, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_CalendarButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_CalendarButton, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_CalendarButton, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SaveTimeButton = lv_button_create(ui_SettingTimeManually);
    lv_obj_set_width(ui_SaveTimeButton, 87);
    lv_obj_set_height(ui_SaveTimeButton, 50);
    lv_obj_set_x(ui_SaveTimeButton, 0);
    lv_obj_set_y(ui_SaveTimeButton, 81);
    lv_obj_set_align(ui_SaveTimeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SaveTimeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_SaveTimeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SaveTimeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SaveTimeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SaveTimeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SaveTimeButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SaveTimeButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_SaveTimeButton, lv_color_hex(0x1200FF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SaveTimeButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_SaveTimeButton, 1, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_color(ui_SaveTimeButton, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_SaveTimeButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_SaveTimeButton, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_SaveTimeButton, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SaveTime = lv_label_create(ui_SaveTimeButton);
    lv_obj_set_width(ui_SaveTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SaveTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveTime, "Exit");
    lv_obj_set_style_text_color(ui_SaveTime, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveTime, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToWelcome2 = lv_imagebutton_create(ui_SettingTimeManually);
    lv_imagebutton_set_src(ui_BackToWelcome2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_388382192, NULL);
    lv_obj_set_width(ui_BackToWelcome2, 32);
    lv_obj_set_height(ui_BackToWelcome2, 32);
    lv_obj_set_align(ui_BackToWelcome2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_outline_color(ui_BackToWelcome2, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_BackToWelcome2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_BackToWelcome2, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_BackToWelcome2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_TimeSetting, ui_event_TimeSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalendarButton, ui_event_CalendarButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveTimeButton, ui_event_SaveTimeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackToWelcome2, ui_event_BackToWelcome2, LV_EVENT_ALL, NULL);

}

void ui_SettingTimeManually_screen_destroy(void)
{
    if(ui_SettingTimeManually) lv_obj_del(ui_SettingTimeManually);

    // NULL screen variables
    ui_SettingTimeManually = NULL;
    ui_HourSetting = NULL;
    ui_Spinbox1 = NULL;
    ui_Spinbox2 = NULL;
    ui_colon = NULL;
    ui_HourLabel = NULL;
    ui_MinuteLabel = NULL;
    ui_TimeSetting = NULL;
    ui_Panel1 = NULL;
    ui_DaySetting = NULL;
    ui_CalendarButton = NULL;
    ui_SaveTimeButton = NULL;
    ui_SaveTime = NULL;
    ui_BackToWelcome2 = NULL;

}
