// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_TIME_H
#define UI_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Time
extern void ui_Time_screen_init(void);
extern void ui_Time_screen_destroy(void);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_WiFiStatus;
extern void ui_event_resync(lv_event_t * e);
extern lv_obj_t * ui_resync;
extern lv_obj_t * ui_HourPanel;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_SolarPanel;
extern lv_obj_t * ui_SolarLabel;
extern lv_obj_t * ui_SolarDay;
extern lv_obj_t * ui_DOW;
extern lv_obj_t * ui_LunarPanel;
extern lv_obj_t * ui_LunarLabel;
extern lv_obj_t * ui_LunarDay;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_HumidIcon;
extern lv_obj_t * ui_DailyTemp;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_TempNow;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_Night;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

