// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_WiFiStatus = NULL;
lv_obj_t * ui_resync = NULL;
lv_obj_t * ui_HourPanel = NULL;
lv_obj_t * ui_Hour = NULL;
lv_obj_t * ui_Second = NULL;
lv_obj_t * ui_Day = NULL;
lv_obj_t * ui_SolarPanel = NULL;
lv_obj_t * ui_SolarLabel = NULL;
lv_obj_t * ui_SolarDay = NULL;
lv_obj_t * ui_DOW = NULL;
lv_obj_t * ui_LunarPanel = NULL;
lv_obj_t * ui_LunarLabel = NULL;
lv_obj_t * ui_LunarDay = NULL;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_DailyTemp = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_TempNow = NULL;
lv_obj_t * ui_Rain = NULL;
lv_obj_t * ui_Night = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_HumidIcon = NULL;
lv_obj_t * ui_Temp = NULL;
// event funtions
void ui_event_resync(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ReSyncManually(e);
    }
}

// build funtions

void ui_Time_screen_init(void)
{
    ui_Time = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_WiFiStatus = lv_label_create(ui_Time);
    lv_obj_set_width(ui_WiFiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatus, 2);
    lv_obj_set_y(ui_WiFiStatus, 2);
    lv_label_set_text(ui_WiFiStatus, "WiFi: No connection");
    ui_object_set_themeable_style_property(ui_WiFiStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_WiFiStatus, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_WiFiStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiStatus, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resync = lv_image_create(ui_Time);
    lv_image_set_src(ui_resync, &ui_img_385938922);
    lv_obj_set_width(ui_resync, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_resync, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_resync, -5);
    lv_obj_set_y(ui_resync, 0);
    lv_obj_set_align(ui_resync, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_resync, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_resync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_resync, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_resync, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_resync, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_resync, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_HourPanel = lv_obj_create(ui_Time);
    lv_obj_set_width(ui_HourPanel, 205);
    lv_obj_set_height(ui_HourPanel, 130);
    lv_obj_set_x(ui_HourPanel, -56);
    lv_obj_set_y(ui_HourPanel, -36);
    lv_obj_set_align(ui_HourPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HourPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_HourPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_HourPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_outline_color(ui_HourPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_HourPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_HourPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_HourPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour = lv_label_create(ui_HourPanel);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "20:00");
    ui_object_set_themeable_style_property(ui_Hour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Hour, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Second = lv_label_create(ui_HourPanel);
    lv_obj_set_width(ui_Second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Second, 81);
    lv_obj_set_y(ui_Second, 8);
    lv_obj_set_align(ui_Second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Second, "00");
    ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Second, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Day = lv_image_create(ui_HourPanel);
    lv_image_set_src(ui_Day, &ui_img_84851999);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Day, -7);
    lv_obj_set_y(ui_Day, 7);
    lv_obj_set_align(ui_Day, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Day, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Day, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SolarPanel = lv_obj_create(ui_Time);
    lv_obj_set_width(ui_SolarPanel, 155);
    lv_obj_set_height(ui_SolarPanel, 80);
    lv_obj_set_x(ui_SolarPanel, -81);
    lv_obj_set_y(ui_SolarPanel, 73);
    lv_obj_set_align(ui_SolarPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SolarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SolarPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_SolarPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_outline_color(ui_SolarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SolarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SolarPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SolarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolarLabel = lv_label_create(ui_SolarPanel);
    lv_obj_set_width(ui_SolarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SolarLabel, -6);
    lv_obj_set_y(ui_SolarLabel, -6);
    lv_label_set_text(ui_SolarLabel, "Solar");
    ui_object_set_themeable_style_property(ui_SolarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_SolarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_SolarLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolarDay = lv_label_create(ui_SolarPanel);
    lv_obj_set_width(ui_SolarDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolarDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SolarDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolarDay, "02-08-2026");
    ui_object_set_themeable_style_property(ui_SolarDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_SolarDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_SolarDay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DOW = lv_label_create(ui_SolarPanel);
    lv_obj_set_width(ui_DOW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DOW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DOW, -6);
    lv_obj_set_y(ui_DOW, 6);
    lv_obj_set_align(ui_DOW, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_DOW, "Sunday");
    ui_object_set_themeable_style_property(ui_DOW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_DOW, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_DOW, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DOW, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LunarPanel = lv_obj_create(ui_Time);
    lv_obj_set_width(ui_LunarPanel, 155);
    lv_obj_set_height(ui_LunarPanel, 80);
    lv_obj_set_x(ui_LunarPanel, 79);
    lv_obj_set_y(ui_LunarPanel, 73);
    lv_obj_set_align(ui_LunarPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LunarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_LunarPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_LunarPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_bg_image_tiled(ui_LunarPanel, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LunarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LunarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LunarPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LunarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LunarLabel = lv_label_create(ui_LunarPanel);
    lv_obj_set_width(ui_LunarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LunarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LunarLabel, -6);
    lv_obj_set_y(ui_LunarLabel, -6);
    lv_label_set_text(ui_LunarLabel, "Lunar");
    ui_object_set_themeable_style_property(ui_LunarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_LunarLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_LunarLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LunarDay = lv_label_create(ui_LunarPanel);
    lv_obj_set_width(ui_LunarDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LunarDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LunarDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LunarDay, "20-06-2026");
    ui_object_set_themeable_style_property(ui_LunarDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_LunarDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_LunarDay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather = lv_obj_create(ui_Time);
    lv_obj_set_width(ui_Weather, 105);
    lv_obj_set_height(ui_Weather, 130);
    lv_obj_set_x(ui_Weather, 103);
    lv_obj_set_y(ui_Weather, -36);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_bg_image_opa(ui_Weather, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Weather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Weather, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Weather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DailyTemp = lv_label_create(ui_Weather);
    lv_obj_set_width(ui_DailyTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DailyTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DailyTemp, 9);
    lv_obj_set_y(ui_DailyTemp, -24);
    lv_obj_set_align(ui_DailyTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DailyTemp, "No info");
    ui_object_set_themeable_style_property(ui_DailyTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_DailyTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_DailyTemp, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Weather);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 7);
    lv_obj_set_y(ui_Humidity, 7);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "No info");
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Rain);
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Rain);
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Humidity, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempNow = lv_label_create(ui_Weather);
    lv_obj_set_width(ui_TempNow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempNow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempNow, 7);
    lv_obj_set_y(ui_TempNow, -45);
    lv_obj_set_align(ui_TempNow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempNow, "No info");
    ui_object_set_themeable_style_property(ui_TempNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_Rain = lv_label_create(ui_Weather);
    lv_obj_set_width(ui_Rain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Rain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Rain, 7);
    lv_obj_set_y(ui_Rain, 39);
    lv_obj_set_align(ui_Rain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Rain, "No info");
    ui_object_set_themeable_style_property(ui_Rain, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Rain);
    ui_object_set_themeable_style_property(ui_Rain, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Rain);

    ui_Night = lv_image_create(ui_Weather);
    lv_image_set_src(ui_Night, &ui_img_night_png);
    lv_obj_set_width(ui_Night, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Night, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Night, 0);
    lv_obj_set_y(ui_Night, 43);
    lv_obj_set_align(ui_Night, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Night, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Night, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Weather);
    lv_image_set_src(ui_Image1, &ui_img_rain_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image1, -35);
    lv_obj_set_y(ui_Image1, 39);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidIcon = lv_image_create(ui_Weather);
    lv_image_set_src(ui_HumidIcon, &ui_img_humidity_png);
    lv_obj_set_width(ui_HumidIcon, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_HumidIcon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_HumidIcon, -35);
    lv_obj_set_y(ui_HumidIcon, 5);
    lv_obj_set_align(ui_HumidIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumidIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_HumidIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temp = lv_image_create(ui_Weather);
    lv_image_set_src(ui_Temp, &ui_img_thermometer_png);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Temp, -35);
    lv_obj_set_y(ui_Temp, -44);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Temp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Temp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_resync, ui_event_resync, LV_EVENT_ALL, NULL);

}

void ui_Time_screen_destroy(void)
{
    if(ui_Time) lv_obj_del(ui_Time);

    // NULL screen variables
    ui_Time = NULL;
    ui_WiFiStatus = NULL;
    ui_resync = NULL;
    ui_HourPanel = NULL;
    ui_Hour = NULL;
    ui_Second = NULL;
    ui_Day = NULL;
    ui_SolarPanel = NULL;
    ui_SolarLabel = NULL;
    ui_SolarDay = NULL;
    ui_DOW = NULL;
    ui_LunarPanel = NULL;
    ui_LunarLabel = NULL;
    ui_LunarDay = NULL;
    ui_Weather = NULL;
    ui_DailyTemp = NULL;
    ui_Humidity = NULL;
    ui_TempNow = NULL;
    ui_Rain = NULL;
    ui_Night = NULL;
    ui_Image1 = NULL;
    ui_HumidIcon = NULL;
    ui_Temp = NULL;

}
