// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#include "ui.h"

lv_obj_t * ui_WiFiSetting = NULL;
lv_obj_t * ui_WiFiList = NULL;
lv_obj_t * ui_WiFiPass = NULL;
lv_obj_t * ui_ConnectButton = NULL;
lv_obj_t * ui_ConnectText = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_MoveToClock = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_BackToWelcome1 = NULL;
// event funtions
void ui_event_WiFiSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        scanWifiCall(e);
    }
}

void ui_event_WiFiPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_WiFiPass);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        groupKeyboard(e);
    }
}

void ui_event_ConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectWifFi(e);
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MoveToClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}

void ui_event_BackToWelcome1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Welcome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Welcome_screen_init);
    }
}

// build funtions

void ui_WiFiSetting_screen_init(void)
{
    ui_WiFiSetting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WiFiSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiList = lv_dropdown_create(ui_WiFiSetting);
    lv_obj_set_width(ui_WiFiList, 230);
    lv_obj_set_height(ui_WiFiList, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_WiFiList, 0);
    lv_obj_set_y(ui_WiFiList, -84);
    lv_obj_set_align(ui_WiFiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_WiFiList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_WiFiList, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_WiFiList, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_WiFiList, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_WiFiList, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_WiFiPass = lv_textarea_create(ui_WiFiSetting);
    lv_obj_set_width(ui_WiFiPass, 230);
    lv_obj_set_height(ui_WiFiPass, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_WiFiPass, 0);
    lv_obj_set_y(ui_WiFiPass, -33);
    lv_obj_set_align(ui_WiFiPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WiFiPass, "Password");
    lv_textarea_set_one_line(ui_WiFiPass, true);
    lv_obj_set_style_border_color(ui_WiFiPass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WiFiPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_WiFiPass, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_WiFiPass, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_WiFiPass, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_WiFiPass, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_bg_color(ui_WiFiPass, lv_color_hex(0x0A0A23), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiPass, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_WiFiPass, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiPass, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_ConnectButton = lv_button_create(ui_WiFiSetting);
    lv_obj_set_width(ui_ConnectButton, 100);
    lv_obj_set_height(ui_ConnectButton, 32);
    lv_obj_set_x(ui_ConnectButton, 0);
    lv_obj_set_y(ui_ConnectButton, 16);
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_ConnectButton, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_ConnectButton, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_ConnectButton, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ConnectText = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_ConnectText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectText, "Connect");
    lv_obj_set_style_text_color(ui_ConnectText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_ConnectText, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_WiFiSetting);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 60);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_MoveToClock = lv_button_create(ui_WiFiSetting);
    lv_obj_set_width(ui_MoveToClock, 230);
    lv_obj_set_height(ui_MoveToClock, 50);
    lv_obj_set_x(ui_MoveToClock, 0);
    lv_obj_set_y(ui_MoveToClock, 70);
    lv_obj_set_align(ui_MoveToClock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MoveToClock, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MoveToClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_MoveToClock);
    lv_obj_set_width(ui_Label8, 220);
    lv_obj_set_height(ui_Label8, 29);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "WiFi is set, click here to move to clock screen");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackToWelcome1 = lv_imagebutton_create(ui_WiFiSetting);
    lv_imagebutton_set_src(ui_BackToWelcome1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_388382192, NULL);
    lv_obj_set_width(ui_BackToWelcome1, 32);
    lv_obj_set_height(ui_BackToWelcome1, 32);
    lv_obj_set_align(ui_BackToWelcome1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_outline_color(ui_BackToWelcome1, lv_color_hex(0x001CFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_BackToWelcome1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_BackToWelcome1, 4, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_BackToWelcome1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_WiFiPass, ui_event_WiFiPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_WiFiPass);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MoveToClock, ui_event_MoveToClock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackToWelcome1, ui_event_BackToWelcome1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiSetting, ui_event_WiFiSetting, LV_EVENT_ALL, NULL);

}

void ui_WiFiSetting_screen_destroy(void)
{
    if(ui_WiFiSetting) lv_obj_del(ui_WiFiSetting);

    // NULL screen variables
    ui_WiFiSetting = NULL;
    ui_WiFiList = NULL;
    ui_WiFiPass = NULL;
    ui_ConnectButton = NULL;
    ui_ConnectText = NULL;
    ui_Keyboard1 = NULL;
    ui_MoveToClock = NULL;
    ui_Label8 = NULL;
    ui_BackToWelcome1 = NULL;

}
