// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_WIFISETTING_H
#define UI_WIFISETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiSetting
extern void ui_WiFiSetting_screen_init(void);
extern void ui_WiFiSetting_screen_destroy(void);
extern void ui_event_WiFiSetting(lv_event_t * e);
extern lv_obj_t * ui_WiFiSetting;
extern lv_obj_t * ui_WiFiList;
extern void ui_event_WiFiPass(lv_event_t * e);
extern lv_obj_t * ui_WiFiPass;
extern void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_ConnectText;
extern void ui_event_BackToWelcome1(lv_event_t * e);
extern lv_obj_t * ui_BackToWelcome1;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_MoveToClock(lv_event_t * e);
extern lv_obj_t * ui_MoveToClock;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

