// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: TFT_28

#ifndef UI_WELCOME_H
#define UI_WELCOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Welcome
extern void ui_Welcome_screen_init(void);
extern void ui_Welcome_screen_destroy(void);
extern lv_obj_t * ui_Welcome;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label12;
extern void ui_event_SettingOption1(lv_event_t * e);
extern lv_obj_t * ui_SettingOption1;
extern lv_obj_t * ui_Label1;
extern void ui_event_SettingOption2(lv_event_t * e);
extern lv_obj_t * ui_SettingOption2;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

